$ANSIBLE_VAULT;1.1;AES256
37373632346464616233333266623964313435306563633564643964626436653639333937373965
6366666464363636663132336535336635643339306430370a623631633265666138363534633435
36646339323937653338643430656535393038653062346537666635636434336464353239326333
3732376131316337640a383334303437353863303939636139626232343433333238306333363533
36623337326565363233393933373933663037383831323039386435626232616236373732346333
39323937333833643039336466653463653664336365363630386365616337386133356363363563
66623964333365366636386332343162386161663736626439303837396539376333663565623166
39613763613332343039353766356234666336626166616237366336393133666266613233633664
63366231313965383665336262376336353162306539656366363962363339363738393961326364
62353332313739646363333262396466353834376238653162303062646663393131373261643866
30646666623930313539373938316230363030306632343839316638326632363238316662366337
62643638373737623734616339656364666330336665663031383835633430616534366561383662
61363039346238393930376138326163366633346331666561616230366339353632343230373034
39353038663237343634623561343766326335373063353235633365306532306463663534326233
38343065323533623339626437356664356230336465366262623933653438326162393363396332
38373337313134656239366563343631343362363063353034373364303639633334663264373834
35303935306665633131396661313262353432646366333236333232626331333162633338623131
62343266383362373836616162663937393761336633366339326363633633643164346537393336
34383963373165333462356666666463323933323763373336643932303738363036653738363132
38343532383061656431633262613031646465633861646333313864333734646666336131363332
64336635333733393939356261616361653236313661646632353966383164663562376532386461
6638663965613163383762376166326131336534373930626661
